/**
 * GTFS index — loaded from pre-generated derived JSON files.
 * Replaces the old approach of streaming the 150 MB stop_times.txt at runtime.
 *
 * Source files are generated by scripts/build_gtfs_derived.py and committed to
 * client/public/gotransit/derived/ so they are available on Vercel.
 *
 * Shared by /api/departures and /api/schedule.
 */

import { readFileSync, statSync } from "fs";
import { join } from "path";

const DERIVED_DIR = join(process.cwd(), "public", "gotransit", "derived");

// ─── Exported types ───────────────────────────────────────────────────────────

export interface DepartureEntry {
  time:        string;  // "HH:MM"
  headsign:    string;
  directionId: number;
  /** First stop name on this trip (board-here origin for departures cards) */
  fromStop?:   string;
}

export interface StopTimeEntry {
  stopId:        string;
  stopName:      string;
  lat:           number;
  lon:           number;
  sequence:      number;
  departureTime: string; // "HH:MM"
  arrivalTime:   string; // "HH:MM"
}

export interface FullIndex {
  /** key: `${routeShortName}|${dayOfWeek}` (JS getDay, 0=Sun) */
  departures:    Map<string, DepartureEntry[]>;
  /** key: representative_trip_id */
  tripStopTimes: Map<string, StopTimeEntry[]>;
}

// ─── Module-level cache ───────────────────────────────────────────────────────

let cachedIndex: FullIndex | null = null;
let cachedIndexDepsMtimeMs = 0;

function derivedDepsMtimeMs(): number {
  try {
    const depPath = join(DERIVED_DIR, "departures_index.json");
    const tripPath = join(DERIVED_DIR, "trip_stop_times.json");
    return Math.max(statSync(depPath).mtimeMs, statSync(tripPath).mtimeMs);
  } catch {
    return 0;
  }
}

function buildIndex(): FullIndex {
  const departuresRaw = JSON.parse(
    readFileSync(join(DERIVED_DIR, "departures_index.json"), "utf-8"),
  ) as Record<string, DepartureEntry[]>;

  const tripStopTimesRaw = JSON.parse(
    readFileSync(join(DERIVED_DIR, "trip_stop_times.json"), "utf-8"),
  ) as Record<string, StopTimeEntry[]>;

  return {
    departures:    new Map(Object.entries(departuresRaw)),
    tripStopTimes: new Map(Object.entries(tripStopTimesRaw)),
  };
}

// ─── Public API ───────────────────────────────────────────────────────────────

export function getFullIndex(): Promise<FullIndex> {
  const mtime = derivedDepsMtimeMs();
  if (!cachedIndex || mtime !== cachedIndexDepsMtimeMs) {
    cachedIndexDepsMtimeMs = mtime;
    cachedIndex = buildIndex();
  }
  return Promise.resolve(cachedIndex);
}

export function isIndexCached(): boolean { return cachedIndex !== null; }
